OPENAI_API_KEY = "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"
BOLT_URL = "bolt://localhost:7687"
USERNAME = "neo4j"
PASSWORD = "pleaseletmein"

ENDPOINT = "https://herogra.openai.azure.com/"
AZURE_API_KEY = "33aac3f8e256483199a00b02a95b40ca"

AZURE_API_KEY_EMBEDDINGS = "258e4fbea23348729231635023f815eb"
ENDPOINT_EMBEDDINGS = "https://embeddings-herogra.openai.azure.com/"

